name: CI/CD Pipeline - Maven, Docker, Kubernetes, Artifactory

on:
  push:
    branches:
      - main  # Ejecutar solo en la rama principal

env:
  IMAGE_NAME: axelvergara/myapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Upload artifact to Artifactory
        run: |
          curl -u ${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_PASSWORD }} \
          -T target/*.jar \
          "https://tu-dominio-artifactory/artifactory/libs-release-local/myapp/" 

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Clean up local Docker cache
        run: docker system prune -af

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config    

      - name: Verify cluster access
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp myapp=$IMAGE_NAME:$IMAGE_TAG    
          kubectl rollout status deployment/myapp